#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|vsphere> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/cf-services-template.yml \
  $templates/cf-infrastructure-${infrastructure}.yml \
  $*
