meta:
  stemcell:
    name: bosh-vsphere-esxi-ubuntu

jobs:
  - name: mysql_gateway
    instances: 1
    networks:
    - name: services_v1_mysql
      static_ips: (( static_ips(10) ))

  - name: mysql_node
    instances: 1
    networks:
    - name: services_v1_mysql
      static_ips: (( static_ips(11) ))

compilation:
  cloud_properties:
    ram: 1024
    disk: 4096
    cpu: 2

networks: (( merge ))

resource_pools:
  - name: services-small
    cloud_properties:
      ram: 1024
      # enough for extracting mysql
      disk: 10480
      cpu: 1

