---
meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

  stemcell:
    name: (( merge ))
    version: latest

name: (( meta.environment "-v1-mysql" ))
director_uuid: (( merge ))

releases:
- name: cf-services
  version: latest

compilation:
  workers: 3
  network: services_v1_mysql
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 30000-600000
  max_in_flight: 4
  max_errors: 1

networks: (( merge ))

resource_pools:
- name: services-small
  network: services_v1_mysql
  size: (( auto ))
  stemcell: (( meta.stemcell ))
  cloud_properties: (( merge ))

jobs:
- name: mysql_gateway
  release: cf-services
  template:
  - mysql_gateway
  instances: 1
  resource_pool: services-small
  networks:
  - name: services_v1_mysql
    static_ips: (( static_ips(10) ))
  properties:
    mysql_gateway:
      token: chuckecheese
      cc_api_version: v2
      check_orphan_interval: 7200
      supported_versions:
      - '5.5'
      version_aliases:
        "current": "5.5"
- name: mysql_node
  release: cf-services
  template:
  - mysql_node
  instances: 1
  resource_pool: services-small
  persistent_disk: 4096
  networks:
  - name: services_v1_mysql
    static_ips: (( static_ips(11) ))
  properties:
    mysql_node:
      plan: "100mb"
      supported_versions:
      - '5.5'

properties:
  system_domain: (( merge ))
  uaa_client_id: "cf"
  uaa_endpoint: (( "http://uaa." system_domain ))
  appdirect_gateway:
    uaa_client_auth_credentials: (( merge ))
  uaa_client_auth_credentials: (( appdirect_gateway.uaa_client_auth_credentials ))
  service_plans:
    mysql:
      "100mb":
        unique_id: '3173ce70-fef2-11e2-b778-0800200c9a66'
        description: "Shared service, 100MB storage, 10 connections per DB"
        extra: '{"cost":0.0,"bullets":[{"content":"100 MB storage"},{"content":"10 connections per DB"}]}'
        configuration:
          capacity: 20
          max_db_size: 100
          innodb_buffer_pool_size: 512
          max_clients: 10
          max_connections: 100
  nats: (( merge ))
  cc:
    srv_api_uri: (( protocol "://api."  system_domain ))
    protocol: (( merge  || "https" ))
