#!/bin/bash
<%
node = properties.mysql_node
%>

JOB_DIR=/var/vcap/jobs/mysql_node
PKG_DIR=/var/vcap/packages/mysql_node
MYSQL_DIR=/var/vcap/packages/mysql
MYSQL55_DIR=/var/vcap/packages/mysql55

SERVICE_NAME="mysql"
SOCKET_FILE=<%= node.warden_socket_path || "/tmp/warden.sock" %>
source /var/vcap/packages/mysql_node/common/services/utils.sh

case $1 in

  start)
    echo "Setup warden."
    setup_warden
    echo "Starting warden."
    start_warden
    ;;

  stop)
    if [ -f /var/vcap/sys/run/warden/warden.pid ]; then
      PIDFILE=/var/vcap/sys/run/warden/warden.pid
    fi
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
